server:
  port: 8301
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
        - id: demo-portal
          uri: lb://demo-portal
          predicates:
            - Path=/demo-portal/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8401/rsa/publicKey'

secure:
  ignore:
    urls: #免校验路径
      - "/auth-service/oauth/token"

